.TH xfs_scrub 8
.SH NAME
xfs_scrub \- scrub the contents of an XFS filesystem
.SH SYNOPSIS
.B xfs_scrub
[
.B \-dvx
] [
.B \-t
.I fstype
]
.I mountpoint
.br
.B xfs_scrub \-V
.SH DESCRIPTION
.B xfs_scrub
attempts to read and check all the metadata in a Linux filesystem.
.PP
If
.B xfs_scrub
does not detect an XFS filesystem, it will use a generic backend to
scrub the filesystem.
This involves walking the directory tree, querying the data and
extended attribute extent maps, performing limited checks of directory
and inode data, reading all of an inode's extended attributes,
optionally reading all data in a file, and comparing the number of
blocks and inodes seen against the reported counters.
.PP
If an XFS filesystem is detected, then
.B xfs_scrub
will use private XFS ioctls to perform more rigorous scrubbing of the
internal metadata.
Currently this is limited to asking the kernel to check the per-AG
btrees, inode data, and realtime metadata.
The in-kernel scrubbers also cross-reference each data structure's
records against the other filesystem metadata.
.SH OPTIONS
.TP
.B \-d
Enable debugging mode, which augments error reports with the exact file
and line where the scrub failure occurred.
This also enables verbose mode.
.TP
.B \-v
Enable verbose mode, which prints periodic status updates.
.TP
.BI \-T
Print timing and memory usage information for each phase.
.TP
.BI \-t " fstype"
Force the use of a particular type of filesystem scrubber.  Currently
supported backends are the
.IR xfs , " ext4" , " ext3", " ext2", " btrfs" ", and " generic
scrubbers.
.TP
.B \-V
Prints the version number and exits.
.TP
.B \-x
Scrub file data.  This reads every block of every file on disk.
If the filesystem reports file extent mappings or physical extent
mappings and is backed by a block device,
.B xfs_scrub
will issue O_DIRECT reads to the block device directly.
If the block device is a SCSI disk, it will issue READ VERIFY commands
directly to the disk.
.SH EXIT CODE
The exit code returned by
.B xfs_scrub
is the sum of the following conditions:
.br
\	0\	\-\ No errors
.br
\	4\	\-\ File system errors left uncorrected
.br
\	8\	\-\ Operational error
.br
\	16\	\-\ Usage or syntax error
.br
.SH CAVEATS
.B xfs_scrub
is an immature utility!
The generic scrub backend walks the directory tree, reads file extents
and data, and queries every extended attribute it can find.
The generic scrub does not grab exclusive locks on the objects it is
examining, nor does it have any way to cross-reference what it sees
against the internal filesystem metadata.
.PP
The XFS backend takes advantage of in-kernel scrubbing to verify a
given data structure with locks held.
This can tie up the system for a while.
.PP
If errors are found, the filesystem should be taken offline and
repaired.
.SH SEE ALSO
.BR xfs_repair (8).
